version: '3.8'

services:
  postgres_db:
    image: postgres:16
    container_name: sql_agent_postgres
    environment:
      POSTGRES_USER: sri_xmlking
      POSTGRES_PASSWORD: dobbei
      POSTGRES_DB: agent_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql_agent_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_user -d agent_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
